# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en -Dfile.encoding=UTF8
org.gradle.daemon=false
#build_command=gradlew publishUnified

minecraft_version=26.1.2
supported_version=26.1.x
neo_version=26.1.2.17-beta
jei_version=29.5.0.26
cloth_config_version=26.1.154
snakeyaml_version=2.0
evalex_version=3.4.0
architectury_version=13.0.8
rei_version=16.0.799
emi_version=1.1.22+1.21.1

mod_version=26.0.7
release_type=beta
mod_id=kiwi