# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G -Xms3G -Duser.language=en
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.1.2
supported_version=26.1.X
archive_minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=26.0.14
release_type=release
mod_id=kiwi
maven_group=snownee.kiwi
archives_base_name=Kiwi

# Dependencies
fabric_api_version=0.146.1+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
rei_version=16.0.729
# https://modmaven.dev/mezz/jei/
jei_version=29.5.0.26
snakeyaml_version=2.6
evalex_version=3.4.0
jade_version=26.0.8
